<a href="https://colab.research.google.com/github/TsubasaMoriguchi/gazo/blob/master/%E7%94%BB%E5%83%8F%E5%88%86%E9%A1%9E_%E5%AD%A6%E7%BF%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import sys
sys.path.append('/content/drive/My Drive/gazo/')

import ic_module as ic

import importlib
importlib.reload(ic)

import os.path as op

i = 0
for filename in ic.FileNames :
    # ディレクトリ名入力
    while True :
        dirname = input(">>「" + ic.ClassNames[i] + "」の画像のあるディレクトリ ： ")
        if op.isdir(dirname) :
            break
        print(">> そのディレクトリは存在しません！")

    # 関数実行
    ic.PreProcess(dirname, filename, var_amount=3)
    i += 1

>>「小松菜奈」の画像のあるディレクトリ ： /content/drive/My Drive/gazo/face/小松菜奈
>> /content/drive/My Drive/gazo/face/小松菜奈から41個のファイル読み込み成功
>>「CR7」の画像のあるディレクトリ ： /content/drive/My Drive/gazo/face/CR7
>> /content/drive/My Drive/gazo/face/CR7から52個のファイル読み込み成功
>>「久保建英」の画像のあるディレクトリ ： /content/drive/My Drive/gazo/face/久保建英
>> /content/drive/My Drive/gazo/face/久保建英から32個のファイル読み込み成功


## 学習

In [10]:
import ic_module as ic

# 関数実行
ic.Learning(tsnum=30, nb_epoch=50, batch_size=8, learn_schedule=0.9)

>> 学習サンプル数 :  (125, 32, 32, 3)
>> 学習開始
Epoch 1/50
4/5 [=======================>......] - ETA: 0s - loss: 1.0515 - accuracy: 0.4688
Epoch 00001: val_loss improved from inf to 1.37198, saving model to best.hdf5
5/5 [==============================] - 1s 125ms/step - loss: 1.0219 - accuracy: 0.4857 - val_loss: 1.3720 - val_accuracy: 0.3333
Epoch 2/50
4/5 [=======================>......] - ETA: 0s - loss: 0.9323 - accuracy: 0.6250
Epoch 00002: val_loss improved from 1.37198 to 1.13489, saving model to best.hdf5
5/5 [==============================] - 0s 88ms/step - loss: 0.9156 - accuracy: 0.6286 - val_loss: 1.1349 - val_accuracy: 0.3333
Epoch 3/50
4/5 [=======================>......] - ETA: 0s - loss: 0.8458 - accuracy: 0.5938
Epoch 00003: val_loss improved from 1.13489 to 1.12369, saving model to best.hdf5
5/5 [==============================] - 0s 90ms/step - loss: 0.8270 - accuracy: 0.6286 - val_loss: 1.1237 - val_accuracy: 0.3333
Epoch 4/50
4/5 [=======================>......] - ETA: 0s 

In [11]:
import ic_module as ic
import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_0.jpg
1
2
3
>> 計算結果↓
[[0.9689061  0.01782745 0.01326635]]
>> この画像は「小松菜奈」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_20.jpg
1
2
3
>> 計算結果↓
[[0.06009116 0.8172122  0.12269668]]
>> この画像は「CR7」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_67.jpg
1
2
3
>> 計算結果↓
[[0.237428   0.5775493  0.18502273]]
>> この画像は「CR7」です。

>> 入力したい画像ファイル(「END」で終了) ： END
