<a href="https://colab.research.google.com/github/TsubasaMoriguchi/gazo/blob/master/%E7%94%BB%E5%83%8F%E5%89%8D%E5%87%A6%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import sys
sys.path.append('/content/drive/My Drive/gazo/face')

import ic_module as ic

import importlib
importlib.reload(ic)

import os.path as op

i = 0
for filename in ic.FileNames :
    # ディレクトリ名入力
    while True :
        dirname = input(">>「" + ic.ClassNames[i] + "」の画像のあるディレクトリ ： ")
        if op.isdir(dirname) :
            break
        print(">> そのディレクトリは存在しません！")

    # 関数実行
    ic.PreProcess(dirname, filename, var_amount=3)
    i += 1

>>「小松菜奈」の画像のあるディレクトリ ： /content/drive/My Drive/gazo/face/小松菜奈
>> /content/drive/My Drive/gazo/face/小松菜奈から41個のファイル読み込み成功
>>「CR7」の画像のあるディレクトリ ： /content/drive/My Drive/gazo/face/CR7
>> /content/drive/My Drive/gazo/face/CR7から52個のファイル読み込み成功
>>「久保建英」の画像のあるディレクトリ ： /content/drive/My Drive/gazo/face/久保建英
>> /content/drive/My Drive/gazo/face/久保建英から32個のファイル読み込み成功


## 学習

In [8]:
import ic_module as ic

# 関数実行
ic.Learning(tsnum=30, nb_epoch=50, batch_size=8, learn_schedule=0.9)

>> 学習サンプル数 :  (125, 32, 32, 3)
>> 学習開始
Epoch 1/50
4/5 [=======================>......] - ETA: 0s - loss: 0.8280 - accuracy: 0.6250
Epoch 00001: val_loss improved from inf to 1.48133, saving model to best.hdf5
5/5 [==============================] - 1s 115ms/step - loss: 1.0164 - accuracy: 0.6000 - val_loss: 1.4813 - val_accuracy: 0.3333
Epoch 2/50
4/5 [=======================>......] - ETA: 0s - loss: 0.8548 - accuracy: 0.6562
Epoch 00002: val_loss improved from 1.48133 to 1.12196, saving model to best.hdf5
5/5 [==============================] - 0s 82ms/step - loss: 0.8429 - accuracy: 0.6286 - val_loss: 1.1220 - val_accuracy: 0.3333
Epoch 3/50
4/5 [=======================>......] - ETA: 0s - loss: 0.8050 - accuracy: 0.5938
Epoch 00003: val_loss did not improve from 1.12196
5/5 [==============================] - 0s 77ms/step - loss: 0.7822 - accuracy: 0.6286 - val_loss: 1.1455 - val_accuracy: 0.3333
Epoch 4/50
4/5 [=======================>......] - ETA: 0s - loss: 0.6692 - accuracy: 0.71

## 試行・実験

In [9]:
import ic_module as ic
import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test
>> そのファイルは存在しません！

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_0.jpg
1
2
3
>> 計算結果↓
[[0.9659305  0.02590892 0.00816054]]
>> この画像は「小松菜奈」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_24.jpg
1
2
3
>> 計算結果↓
[[0.05420639 0.83065087 0.11514269]]
>> この画像は「CR7」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_45.jpg
1
2
3
>> 計算結果↓
[[0.00121562 0.9906997  0.00808472]]
>> この画像は「CR7」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_58.jpg
1
2
3
>> 計算結果↓
[[0.65064186 0.29156578 0.0577924 ]]
>> この画像は「小松菜奈」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_65.jpg
1
2
3
>> 計算結果↓
[[0.24234958 0.59934753 0.15830287]]
>> この画像は「CR7」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo/face/test/image_67.jpg
1
2
3
>> 計算結果↓
[[0.2622476  0.6287469  0.10900549]]
>> この画像は「CR7」です。

>> 入力したい画像ファイル(「END